### PR TITLE
Update s3-sync.scrbl

### PR DESCRIPTION
**Pull request by rfindler**
Should be `log-info` not `log`.

### CODE REVIEW

**Comment by rfindler** [comment]
But it might be better if it was `info@s3-sync` and not just info, as there is a lot of stuff on info. (Looking at the logs for a little example I did, I'm thinking maybe I should change `collabsible-value-bailout` ...)

**Comment by mflatt** [comment]
Maybe it's confusing that the function argument is called `log-info`. That argument's default does log to `info@s3-syc`, although the documentation isn't clear on that point, since it doesn't define `log-s3-sync-info`.

**Comment by rfindler** [comment]
Oh! I missed that. But currently the docs seem to link to the log function,
which isn't right, I believe.

Robby

**Comment by mflatt** [comment]
Right - thanks!

**Pull request merged**
